In [61]:
import pandas as pd

# Data Path
data_path = "/workspace/company/math_scoring_with_gpt/data/number_2.tsv"

# Load Data
df = pd.read_csv(data_path, sep="\t")

# 2

In [62]:
df.head()

,user_id,답안,기호를 정확히 찾을 수 있는가?,각 선분에 대응하는 용어를 정확히 아는가?,각 선분에 대응하는 길이를 올바르게 구하는가?
0,1,"선분 ㄱㄹ, None, 6m\n선분 ㄴㄷ, None, 14m\n선분 ㄱㅁ, None...",NaN,NaN,NaN
1,2,"선분 ㄱㄹ, 윗변, 6cm\n선분 ㄴㄷ, 아랫변, 14cm\n선분 ㄱㅁ, 높이, 6cm",NaN,NaN,NaN
2,3,"선분 ㄱㄹ, 윗변, 6m\n선분 ㄴㄷ, 아랫변, 14m\n선분 ㄱㅁ, 높이, 6m",NaN,NaN,NaN
3,4,"선분 ㄱㄹ, 윗변, 6m\n선분 ㄴㄷ, 아랫변, 14m\n선분 ㄱㅁ, 높이, 6m",NaN,NaN,NaN
4,5,"선분 ㄱㄹ, 윗변, 6m\n선분 ㄴㄷ, 아랫변, 14m\n선분 ㄱㅁ, 높이, 6m",NaN,NaN,NaN

In [71]:
answer1 = []
answer2 = []
answer3 = []

for row in df.iterrows():

    answer1_list = []
    answer2_list = []
    answer3_list = []

    for i in str(row[1]['답안']).split("\n"):
        ##print("row: ", row[1]['user_id'])
        answer1_list.append(str(i).split(",")[0])
        answer2_list.append(str(i).split(",")[1])
        answer3_list.append(str(i).split(",")[2])

    answer1.append(", ".join(answer1_list).replace("\n", ""))
    answer2.append(", ".join(answer2_list).replace("\n", ""))
    answer3.append(", ".join(answer3_list).replace("\n", ""))

print(len(answer1))
print(len(answer2))
print(len(answer3))

df['답안1'] = answer1
df['답안2'] = answer2
df['답안3'] = answer3

df.head()

380
380
380

,user_id,답안,기호를 정확히 찾을 수 있는가?,각 선분에 대응하는 용어를 정확히 아는가?,각 선분에 대응하는 길이를 올바르게 구하는가?,답안1,답안2,답안3
0,1,"선분 ㄱㄹ, None, 6m\n선분 ㄴㄷ, None, 14m\n선분 ㄱㅁ, None...",NaN,NaN,NaN,"선분 ㄱㄹ, 선분 ㄴㄷ, 선분 ㄱㅁ","None, None, None","6m, 14m, 6m"
1,2,"선분 ㄱㄹ, 윗변, 6cm\n선분 ㄴㄷ, 아랫변, 14cm\n선분 ㄱㅁ, 높이, 6cm",NaN,NaN,NaN,"선분 ㄱㄹ, 선분 ㄴㄷ, 선분 ㄱㅁ","윗변, 아랫변, 높이","6cm, 14cm, 6cm"
2,3,"선분 ㄱㄹ, 윗변, 6m\n선분 ㄴㄷ, 아랫변, 14m\n선분 ㄱㅁ, 높이, 6m",NaN,NaN,NaN,"선분 ㄱㄹ, 선분 ㄴㄷ, 선분 ㄱㅁ","윗변, 아랫변, 높이","6m, 14m, 6m"
3,4,"선분 ㄱㄹ, 윗변, 6m\n선분 ㄴㄷ, 아랫변, 14m\n선분 ㄱㅁ, 높이, 6m",NaN,NaN,NaN,"선분 ㄱㄹ, 선분 ㄴㄷ, 선분 ㄱㅁ","윗변, 아랫변, 높이","6m, 14m, 6m"
4,5,"선분 ㄱㄹ, 윗변, 6m\n선분 ㄴㄷ, 아랫변, 14m\n선분 ㄱㅁ, 높이, 6m",NaN,NaN,NaN,"선분 ㄱㄹ, 선분 ㄴㄷ, 선분 ㄱㅁ","윗변, 아랫변, 높이","6m, 14m, 6m"

In [72]:
# save result
save_path = "/workspace/company/math_scoring_with_gpt/data/number_2.tsv"
df.to_csv(save_path, sep="\t", index=False)