In [61]:
import pandas as pd

# Data Path
data_path = "/workspace/company/math_scoring_with_gpt/data/number_2.tsv"

# Load Data
df = pd.read_csv(data_path, sep="\t")

# 2

In [62]:
df.head()

,user_id,답안,기호를 정확히 찾을 수 있는가?,각 선분에 대응하는 용어를 정확히 아는가?,각 선분에 대응하는 길이를 올바르게 구하는가?
0,1,"선분 ㄱㄹ, None, 6m\n선분 ㄴㄷ, None, 14m\n선분 ㄱㅁ, None...",NaN,NaN,NaN
1,2,"선분 ㄱㄹ, 윗변, 6cm\n선분 ㄴㄷ, 아랫변, 14cm\n선분 ㄱㅁ, 높이, 6cm",NaN,NaN,NaN
2,3,"선분 ㄱㄹ, 윗변, 6m\n선분 ㄴㄷ, 아랫변, 14m\n선분 ㄱㅁ, 높이, 6m",NaN,NaN,NaN
3,4,"선분 ㄱㄹ, 윗변, 6m\n선분 ㄴㄷ, 아랫변, 14m\n선분 ㄱㅁ, 높이, 6m",NaN,NaN,NaN
4,5,"선분 ㄱㄹ, 윗변, 6m\n선분 ㄴㄷ, 아랫변, 14m\n선분 ㄱㅁ, 높이, 6m",NaN,NaN,NaN

In [71]:
answer1 = []
answer2 = []
answer3 = []

for row in df.iterrows():

    answer1_list = []
    answer2_list = []
    answer3_list = []

    for i in str(row[1]['답안']).split("\n"):
        ##print("row: ", row[1]['user_id'])
        answer1_list.append(str(i).split(",")[0])
        answer2_list.append(str(i).split(",")[1])
        answer3_list.append(str(i).split(",")[2])

    answer1.append(", ".join(answer1_list).replace("\n", ""))
    answer2.append(", ".join(answer2_list).replace("\n", ""))
    answer3.append(", ".join(answer3_list).replace("\n", ""))

print(len(answer1))
print(len(answer2))
print(len(answer3))

df['답안1'] = answer1
df['답안2'] = answer2
df['답안3'] = answer3

df.head()

380
380
380

,user_id,답안,기호를 정확히 찾을 수 있는가?,각 선분에 대응하는 용어를 정확히 아는가?,각 선분에 대응하는 길이를 올바르게 구하는가?,답안1,답안2,답안3
0,1,"선분 ㄱㄹ, None, 6m\n선분 ㄴㄷ, None, 14m\n선분 ㄱㅁ, None...",NaN,NaN,NaN,"선분 ㄱㄹ, 선분 ㄴㄷ, 선분 ㄱㅁ","None, None, None","6m, 14m, 6m"
1,2,"선분 ㄱㄹ, 윗변, 6cm\n선분 ㄴㄷ, 아랫변, 14cm\n선분 ㄱㅁ, 높이, 6cm",NaN,NaN,NaN,"선분 ㄱㄹ, 선분 ㄴㄷ, 선분 ㄱㅁ","윗변, 아랫변, 높이","6cm, 14cm, 6cm"
2,3,"선분 ㄱㄹ, 윗변, 6m\n선분 ㄴㄷ, 아랫변, 14m\n선분 ㄱㅁ, 높이, 6m",NaN,NaN,NaN,"선분 ㄱㄹ, 선분 ㄴㄷ, 선분 ㄱㅁ","윗변, 아랫변, 높이","6m, 14m, 6m"
3,4,"선분 ㄱㄹ, 윗변, 6m\n선분 ㄴㄷ, 아랫변, 14m\n선분 ㄱㅁ, 높이, 6m",NaN,NaN,NaN,"선분 ㄱㄹ, 선분 ㄴㄷ, 선분 ㄱㅁ","윗변, 아랫변, 높이","6m, 14m, 6m"
4,5,"선분 ㄱㄹ, 윗변, 6m\n선분 ㄴㄷ, 아랫변, 14m\n선분 ㄱㅁ, 높이, 6m",NaN,NaN,NaN,"선분 ㄱㄹ, 선분 ㄴㄷ, 선분 ㄱㅁ","윗변, 아랫변, 높이","6m, 14m, 6m"

In [72]:
# save result
save_path = "/workspace/company/math_scoring_with_gpt/data/number_2.tsv"
df.to_csv(save_path, sep="\t", index=False)

# 5번 전처리

In [1]:
import pandas as pd

# Data Path
data_path = "/workspace/company/math_scoring_with_gpt/data/number_5.xlsx"

# Excel 파일 읽기
df = pd.read_excel(data_path)

# 데이터 출력
print(df)

     user_id                                         답안
0          1                          식: None\n풀이: None  \
1          2                          식: None\n풀이: None
2          3                          식: None\n풀이: None
3          4                          식: None\n풀이: None
4          5                          식: None\n풀이: None
..       ...                                        ...
375      376                                       none
376      377      식: 평행사변형의 넓이 = 밑변 * 높이\n풀이: 20*3 = 60
377      378  식: 평행사변형의 넓이 = 밑변 * 높이\n풀이: (14+6)*3 = 60
378      379      식: 평행사변형의 넓이 = 밑변 * 높이\n풀이: 20*3 = 60
379      380      식: 평행사변형의 넓이 = 밑변 * 높이\n풀이: 20*3 = 60

                                                  텍스트화
0                                                  NaN  \
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
375                                                NaN
376  사다리꼴을 높이의 반이 되도록 윗부분을 180도 회전하여 아랫부분과 연결하여 평행사...
377                                                NaN
378  사다리꼴을 높이의 반이 되도록 윗부분을 180도 회전하여 아랫부분과 연결하여 평행사...
379  사다리꼴을 높이의 반이 되도록 윗부분을 180도 회전하여 아랫부분과 연결하여 평행사...

     정답과 식을 정확히 서술하여 해결하였는가?  문제해결 방법이 적절한가?
0                        NaN             NaN
1                        NaN             NaN
2                        NaN             NaN
3                        NaN             NaN
4                        NaN             NaN
..                       ...             ...
375                      NaN             NaN
376                      NaN             NaN
377                      NaN             NaN
378                      NaN             NaN
379                      NaN             NaN

[380 rows x 5 columns]

In [2]:
save_path = "/workspace/company/math_scoring_with_gpt/data/number_5.tsv"

df.to_csv(save_path, sep="\t", index=False)